databases:
  - name: render_aswin_production_db
    databaseName: render_aswin_production_db_o9ma
    user: aswin_ryuk_production

services:
  - type: web
    name: mini-application
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render_aswin_production_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false